package cn.mcandroid.pojo;

import java.util.Date;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collection_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer collectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.collection_date
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Date collectionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collection_id
     *
     * @return the value of collection.collection_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collection_id
     *
     * @param collectionId the value for collection.collection_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.content_id
     *
     * @return the value of collection.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.content_id
     *
     * @param contentId the value for collection.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.collection_date
     *
     * @return the value of collection.collection_date
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Date getCollectionDate() {
        return collectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.collection_date
     *
     * @param collectionDate the value for collection.collection_date
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setCollectionDate(Date collectionDate) {
        this.collectionDate = collectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}