package cn.mcandroid.pojo;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer columnId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.user_id
     *
     * @return the value of manager.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.user_id
     *
     * @param userId the value for manager.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.column_id
     *
     * @return the value of manager.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.column_id
     *
     * @param columnId the value for manager.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }
}