package cn.mcandroid.pojo;

import java.util.Date;

public class ThematicColumn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_column.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_column.column_name
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_column.description
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_column.column_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Date columnCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_column.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_column.column_id
     *
     * @return the value of thematic_column.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_column.column_id
     *
     * @param columnId the value for thematic_column.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_column.column_name
     *
     * @return the value of thematic_column.column_name
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_column.column_name
     *
     * @param columnName the value for thematic_column.column_name
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_column.description
     *
     * @return the value of thematic_column.description
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_column.description
     *
     * @param description the value for thematic_column.description
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_column.column_createdate
     *
     * @return the value of thematic_column.column_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Date getColumnCreatedate() {
        return columnCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_column.column_createdate
     *
     * @param columnCreatedate the value for thematic_column.column_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setColumnCreatedate(Date columnCreatedate) {
        this.columnCreatedate = columnCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_column.user_id
     *
     * @return the value of thematic_column.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_column.user_id
     *
     * @param userId the value for thematic_column.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}