package cn.mcandroid.pojo;

import java.util.Date;

public class ThematicContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.content_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private Date contentCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.content_title
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private String contentTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thematic_content.thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    private String thematicContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.content_id
     *
     * @return the value of thematic_content.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.content_id
     *
     * @param contentId the value for thematic_content.content_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.column_id
     *
     * @return the value of thematic_content.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.column_id
     *
     * @param columnId the value for thematic_content.column_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.user_id
     *
     * @return the value of thematic_content.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.user_id
     *
     * @param userId the value for thematic_content.user_id
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.content_createdate
     *
     * @return the value of thematic_content.content_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public Date getContentCreatedate() {
        return contentCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.content_createdate
     *
     * @param contentCreatedate the value for thematic_content.content_createdate
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setContentCreatedate(Date contentCreatedate) {
        this.contentCreatedate = contentCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.content_title
     *
     * @return the value of thematic_content.content_title
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public String getContentTitle() {
        return contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.content_title
     *
     * @param contentTitle the value for thematic_content.content_title
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setContentTitle(String contentTitle) {
        this.contentTitle = contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thematic_content.thematic_content
     *
     * @return the value of thematic_content.thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public String getThematicContent() {
        return thematicContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thematic_content.thematic_content
     *
     * @param thematicContent the value for thematic_content.thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    public void setThematicContent(String thematicContent) {
        this.thematicContent = thematicContent;
    }
}