package cn.mcandroid.dao;

import cn.mcandroid.pojo.Replies;
import cn.mcandroid.pojo.RepliesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepliesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    long countByExample(RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByExample(RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByPrimaryKey(Integer repliesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insert(Replies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insertSelective(Replies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    List<Replies> selectByExampleWithBLOBs(RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    List<Replies> selectByExample(RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    Replies selectByPrimaryKey(Integer repliesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Replies record, @Param("example") RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Replies record, @Param("example") RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExample(@Param("record") Replies record, @Param("example") RepliesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKeySelective(Replies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Replies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replies
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKey(Replies record);
}