package cn.mcandroid.dao;

import cn.mcandroid.pojo.ThematicContent;
import cn.mcandroid.pojo.ThematicContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThematicContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    long countByExample(ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByExample(ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insert(ThematicContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insertSelective(ThematicContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    List<ThematicContent> selectByExampleWithBLOBs(ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    List<ThematicContent> selectByExample(ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    ThematicContent selectByPrimaryKey(Integer contentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") ThematicContent record, @Param("example") ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ThematicContent record, @Param("example") ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExample(@Param("record") ThematicContent record, @Param("example") ThematicContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKeySelective(ThematicContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ThematicContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_content
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKey(ThematicContent record);
}