package cn.mcandroid.dao;

import cn.mcandroid.pojo.ThematicColumn;
import cn.mcandroid.pojo.ThematicColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThematicColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    long countByExample(ThematicColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByExample(ThematicColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int deleteByPrimaryKey(Integer columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insert(ThematicColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int insertSelective(ThematicColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    List<ThematicColumn> selectByExample(ThematicColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    ThematicColumn selectByPrimaryKey(Integer columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") ThematicColumn record, @Param("example") ThematicColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByExample(@Param("record") ThematicColumn record, @Param("example") ThematicColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKeySelective(ThematicColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thematic_column
     *
     * @mbg.generated Tue Nov 27 09:47:32 CST 2018
     */
    int updateByPrimaryKey(ThematicColumn record);
}